# Site
repository: sjakka9/PortfolioSushmithaJakka
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Jakka Sushmitha
title: Senior Software Engineer
email: jakkasushmitha18@gmail.com
# email_title: Email (Email title override)
phone: +1-8147613209
# phone_title: Phone (Phone title override)
#website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: jekyllrb
github_username:  sjakka9
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: sushmitha-jakka
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/SushmithaJakka.jpeg
about_content: | # this will include new lines to allow paragraphs
  You can call me Jakka and I am a Graduate Teaching Assistant at the University at Buffalo working in the fields of Statistical Data Mining and Data Model Query Language under Professors Dr.Sreyasee and Dr.Leonid Khinkis.

  ## Technical Proficiency
  - Proficient in a variety of programming languages and frameworks including C#, WPF, WCF, MVVM, .Net Core, ASP.NET MVC, Web API, Entity Framework, ADO.NET, Angular8 and Python.
  - Demonstrated practical skills in Finance, Banking, Industrial, and Trading sports domains, applying technical knowledge effectively in real-world scenarios.
  - Proven track record of contributing to technology migration projects, showcasing adaptability and proficiency in transitioning applications to newer platforms seamlessly.

content:
  - title: Academic Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:    
      - layout: left
        #border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: EPIC Games - Comprehensive Data & Analysis Database Management System with Interactive website.
        #link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #link_text: Link Text
        #additional_links:
          #- title:  Github page for project (eg. sproogen/modern-resume-theme)
            #icon: fab fa-github
            #url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          #- title:  Github page for project (eg. sproogen/modern-resume-theme)
            #icon: fab fa-github
            #url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Revamp Epic gaming data management with a dynamic player database system.
        description: | # this will include new lines to allow paragraphs
          ◦ Created and maintained a Epic Gaming database from scratch using database design theory. This involves data messaging using Python, modeling E/R diagrams, and translating it into a relational schema.
          
          ◦ Analyzed functional dependencies and normalized the tables to eliminate data redundancies and anomalies.
          
          ◦ Formulated and executed a variety of SQL queries to address common retail scenarios, and optimized queries for efficient data retrieval.
          
          ◦ Designed and created an interactive website using HTML5, CSS3, JavaScript, NodeJS, and PyFlask that provides visual insights into the database, showcasing different stats.

  - title: Work Experience
    layout: list
    content:
      - layout: right
        title: University at Buffalo
        sub_title: Graduate Teaching Assistant
        caption: Jan 2024 - Present
        link: https://www.buffalo.edu
        #quote: >
          #Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          ◦ Played a pivotal role in two key courses: Data Model Query Language, and Statistical Data Mining.
          
          ◦ Facilitated weekly practical sessions, enabling students to gain hands-on experience and deepen their understanding of course materials.
          
          ◦ Evaluated and assessed students’ assignments, exams, and projects related to the course.
          
          ◦ Managed a diverse cohort of 250 students.
      - layout: right
        title: IVY Comptech
        sub_title: Senior Software Engineer
        caption: August 2021 - January 2023
        link: https://ivy.global/
        #quote: >
          #Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          ◦ Acquired expertise in the betting and gaming domain, facilitating a deep understanding of Trading Sports Software.

          ◦ Led initiatives to modernize legacy applications, overseeing the seamless transition from .NET Framework 4 to the latest .NET 7, ensuring compatibility and optimizing performance.

          ◦ Spearheaded the migration from Tibco to Kafka signalling systems, enhancing application interactivity and real-time data processing capabilities, thereby improving overall performance and user experience.

          ◦ Successfully orchestrated the conversion of WCF services to RESTful APIs, modernizing communication protocols and improving interoperability across systems.

          ◦ Implemented and maintained Elastic Search for log aggregation and analysis, utilizing Kibana to quickly identify anomalies and troubleshoot system issues.

          ◦ Transitioned from traditional legacy systems to NoSQL databases, gaining hands-on experience with Redis and Cassandra.

          ◦ Implemented CI/CD pipelines using Azure DevOps, enhancing automation and efficiency in software deployment processes.

          ◦ Implemented sophisticated performance monitoring solutions, leveraging high-end performance counters to monitor system load and proactively alert stakeholders via email, ensuring optimal system performance and reliability.

          ◦ Fostered strong collaboration with the product team, maintaining open communication channels to quickly gather and understand requirements, ensuring alignment between development efforts and business objectives.
      - layout: right
        title: NCR Corporation India Pvt Ltd.
        sub_title: PS Software Engineer II
        caption: September 2019 - June 2021
        link: https://www.ncr.com/
        #quote: >
          #Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          ◦ Multicurrency Exchange Terminal Development:

             - One of the standout accomplishments was the conception and development of Multicurrency ATM application, engineered to function as a dynamic foreign exchange counter.

             - This groundbreaking application boasted support for up to 10 input currencies and offered adaptable output options, enabling users to obtain their preferred currency combinations seamlessly.

             - Leveraging cutting-edge technologies such as WPF and MVVM, I meticulously crafted intuitive user interfaces that revolutionized the banking experience for Emirates National Bank of Dubai's clientele.

             - I collaborated closely with the Emirates National Bank of Dubai team at their headquarters, ensuring that the Multicurrency application not only met but exceeded their unique requirements.

             - This collaborative effort culminated in the successful showcasing of our innovative solution at the prestigious Dubai Expo 2020.

             - Our solution received a lot of praise for its advanced features and effectiveness in meeting the changing needs of modern banking. 
          
          ◦ APTRA Activate Enterprise:

            - Led the deployment and customization of APTRA Activate to APTRA Activate Enterprise, an advanced ATM software by NCR. 

            - Spearheaded the transition of the APTRA Activate application from WPF to Angular8.
            
            - I took the lead in handling changes and updates for the ATM application at Emirates National Bank of Dubai.

            - This involved implementing UI enhancements and internal logic modifications to optimize cash withdrawal and deposit processes, thereby enhancing operational efficiency and customer satisfaction.      
      - layout: right
        title: Hexagon Capability Center India Pvt Ltd.
        sub_title: Senior Software Analyst
        caption: October 2016 - September 2019 
        link: https://hexagon.com/company/careers/capability-centre-india
        #quote: >
          #Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          ◦ Contributed to Hexagon PPM's project focusing on Smart3D and CloudWorx for Smart3D products, emphasizing laser scanning technology.

          ◦ Laser scanning is recognized for its precision, comprehensiveness, and cost efficiency in capturing and utilizing as-built data for existing facilities.

          ◦ Transitioned codebase from VB.Net to C#.Net. and Upgraded frontend from WinForms to WPF for a modernized user experience. Integrated DevExpress and Telerik UI components to enhance the visual appeal and functionality.

          ◦ Updated approximately 30 NuGet packages to ensure compatibility with the latest .NET framework.

          ◦ Managed MS Build configurations and automated build and deployment strategies.

          ◦ Utilized 'Coverity' by Synopsys for static code analysis, identifying and fixing bugs to enhance software stability.

          ◦ Worked closely with UX designers and Product Managers to align development efforts with user-centric design principles.

          ◦ Orchestrated on-site interactions with the USA team to clarify requirements and streamline communication channels.

          ◦ Developed unit-test code using NUnit framework to ensure reliability and resilience of C# codebase.

          ◦ Independently managed the entire task, resulting in a notable 30% improvement in application performance.

          ◦ I was honored with the Hexagon Star Award in recognition of my ability to quickly grasp new concepts and execute tasks with precision.

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: University at Buffalo
        sub_title: Master of Science, Data Science
        caption: 2023 - 2024
        #quote: >
          #Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Graduated with CGPA of 3.93/4

          Worked as a Graduate Teaching Assistant

      - layout: top-right
        title: Osmania University
        sub_title: Bachelor of Technology, Computer Science and Engineering
        caption: 2012 - 2016
        #quote: >
          #Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Graduated with a CGPA of 9/10.
          
          Osmania Univeristy Gold Medalist.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
